services:
  - type: web
    name: zayra-core-api
    runtime: docker
    plan: free
    repo: https://github.com/ajrash1714/zayra-core-api
    branch: mai
        envVars:
      - key: PORT
        value: "8000"
