services:
  - type: web
    name: zayra-core-api
    runtime: docker
    plan: free
    repo: https://github.com/ajrash1714/zayra-core-api
    branch: main
    buildCommand: echo "Building Docker image"
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: "8000"
